version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_konnect
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: konnect_db
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - konnectdb_data:/data/db
    networks:
      - app-network
  api-konnect:
    container_name: api-konnect
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always
    networks:
      - app-network
  client-konnect:
    container_name: client-konnect
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  konnectdb_data:
    driver: local
